export const INTERVIEWERS = [
  {
    id: '7456723652143398963',
    name: 'James Chen',
    title: 'Java技术专家',
    company: 'ByteDance',
    avatar: '/images/interviewers/male1.jpg',
    description: '8年Java开发经验，专注于分布式系统和高并发架构设计',
    tags: ['Java', 'Spring Boot', '分布式系统'],
    type: 'coze',
    experience: 8,
    rating: 4.9,
    online: true,
    styles: ['注重基础原理', '关注技术深度', '善于引导思考'],
    direction: '后端开发'
  },
  {
    id: '7487435880626520104',
    name: 'Sarah Zhang',
    title: '前端架构师',
    company: 'Alibaba',
    avatar: '/images/interviewers/female1.jpg',
    description: '6年前端开发经验，精通现代前端框架和工程化实践',
    tags: ['Vue', 'React', '前端工程化'],
    type: 'coze',
    experience: 6,
    rating: 4.8,
    online: true,
    styles: ['擅长实战分析', '全面考察技能', '关注工程实践'],
    direction: '前端开发'
  },
  {
    id: '7487438797861765172',
    name: 'Michael Wang',
    title: '算法专家',
    company: 'Google',
    avatar: '/images/interviewers/male2.jpg',
    description: '算法竞赛金牌得主，专注于机器学习和算法优化',
    tags: ['算法设计', '机器学习', '性能优化'],
    type: 'coze',
    experience: 7,
    rating: 4.9,
    online: true,
    styles: ['思维导向', '重视逻辑性', '关注性能优化'],
    direction: '算法'
  },
  {
    id: '7487443586141716480',
    name: 'Emma Davis',
    title: '系统架构师',
    company: 'Microsoft',
    avatar: '/images/interviewers/female2.jpg',
    description: '10年系统架构经验，专注于大规模分布式系统设计',
    tags: ['系统设计', '架构设计', '微服务'],
    type: 'coze',
    experience: 10,
    rating: 4.95,
    online: true,
    styles: ['系统性思维', '注重可扩展性', '关注技术选型'],
    direction: '系统架构'
  },
  {
    id: '7487473340370747402',
    name: 'David Liu',
    title: '后端开发专家',
    company: 'Tencent',
    avatar: '/images/interviewers/male3.jpg',
    description: '7年后端开发经验，专注于高并发系统和数据库优化',
    tags: ['Go', 'MySQL', '系统优化'],
    type: 'coze',
    experience: 7,
    rating: 4.85,
    online: true,
    styles: ['实践导向', '注重性能', '关注可用性'],
    direction: '后端开发'
  }
] 